# This is a basic workflow to help you get started with Actions

name: Build test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches:
    - test-branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: 
    - ubuntu-latest
    - windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Compilar e Executar
        run: |
         java ParqueDeDiversoes.java
         java ParqueDeDiversoes.java > output.txt

      - name: Verificar Saída
        run: cat output.txt | grep "Funcionou"
